import { Brand, Category, Product, SiteSettings } from "./types";

// Valores usados enquanto o Supabase não está configurado, ou como
// fallback caso a tabela site_settings ainda não tenha sido criada/rodada.
export const defaultSiteSettings: SiteSettings = {
  phone: "(17) 3216-5760",
  whatsapp_number: "5517981548788",
  whatsapp_display: "(17) 98154-8788",
  email: "hidro.g@hotmail.com",
  address: "Rua Feres Bucater, nº 1461 - São José do Rio Preto - SP",
  instagram_url: "https://instagram.com/hidrogbombas",
  facebook_url: "https://facebook.com/hidrogbombas",
};

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Bombas Submersas", slug: "bombas-submersas", image_url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-2", name: "Bomba Drenagem", slug: "bomba-drenagem", image_url: "https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-3", name: "Cabos PP", slug: "cabos-pp", image_url: "https://images.unsplash.com/photo-1621905252507-c6a3569e8c4c?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-4", name: "Conexões", slug: "conexoes", image_url: "https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-5", name: "Painel", slug: "painel", image_url: "https://images.unsplash.com/photo-1581092160607-ee22731cf1e1?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-6", name: "Tampas", slug: "tampas", image_url: "https://images.unsplash.com/photo-1581093458791-9d42e3f0de5c?w=600", parent_id: null, show_in_menu: true },
  { id: "cat-7", name: "Ferramentas", slug: "ferramentas", image_url: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600", parent_id: null, show_in_menu: true },
];

export const mockBrands: Brand[] = [
  { id: "brand-1", name: "Anauger", slug: "anauger", logo_url: null },
  { id: "brand-2", name: "Bombas Leão", slug: "bombas-leao", logo_url: null },
  { id: "brand-3", name: "Condumig", slug: "condumig", logo_url: null },
  { id: "brand-4", name: "Ebara", slug: "ebara", logo_url: null },
  { id: "brand-5", name: "Fundição Medeiros", slug: "fundicao-medeiros", logo_url: null },
  { id: "brand-6", name: "Hidro G", slug: "hidro-g", logo_url: null },
  { id: "brand-7", name: "Mipel", slug: "mipel", logo_url: null },
  { id: "brand-8", name: "Schneider", slug: "schneider", logo_url: null },
  { id: "brand-9", name: "Tupy", slug: "tupy", logo_url: null },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Bomba Submersa Ebara 4\" 4BPL3-10 1,5 CV 220V",
    slug: "bomba-submersa-ebara-4bpl3-10",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-14 0,75 CV </p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-14<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,75 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 14<br />\r\nTensão: 127 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 80 mca<br />\r\nVazão </p>\r\n\r\n<p>80 mts - 1000 L/H</p>\r\n\r\n<p>44 mts - 2500 L/H</p>\r\n\r\n<p>1,4 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-4",
    sku: "4BPL3-10",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/51091860/1-w6q6hbqeh6.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/51091860/1-w6q6hbqeh6.png"],
    specs: [{ spec_name: "Potência", spec_value: "1,5 CV" }, { spec_name: "Tensão", spec_value: "220V 2 FIOS" }, { spec_name: "Amperagem", spec_value: "10,6 A" }, { spec_name: "Profundidade máxima", spec_value: "113 m" }, { spec_name: "Diâmetro mínimo do poço", spec_value: "4\"" }],
    variations: [{ id: "vg-prod-1-1", name: "Energia", options: [{ id: "vo-prod-1-1-1", value: "220 MONO 2 Fios", price_delta: 0 }, { id: "vo-prod-1-1-2", value: "220 TRIF", price_delta: 0 }] }],
  },
  {
    id: "prod-2",
    name: "Bomba Submersa Ebara 4\" 4BPL6-08 1,5 CV 220V",
    slug: "bomba-submersa-ebara-4bpl6-08",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-10 0,50 CV </p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-10<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,50 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 10<br />\r\nTensão: 127 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 57 mca<br />\r\nVazão </p>\r\n\r\n<p>57 mts - 1000 L/H</p>\r\n\r\n<p>33 mts - 2500 L/H</p>\r\n\r\n<p>1,8 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-4",
    sku: "4BPL6-08",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/51090240/1-357njneuwi.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/51090240/1-357njneuwi.png"],
    specs: [{ spec_name: "Potência", spec_value: "1,5 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-3",
    name: "Bomba Submersa Leão 6\" R11A-07 4,5CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r11a-07-600",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R11A-09 6CV 220/380 TRIF s600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R11A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 6CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 19,73A / 11,59A</p>\r\n\r\n<p>Profundidade Max: 120 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">120 Metros - 6000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">103 Metros - 10000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">72 Metros - 14000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R11A-07-600",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/31138374/1-411qbqv2ed.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/31138374/1-411qbqv2ed.png"],
    specs: [{ spec_name: "Potência", spec_value: "4,5 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-4",
    name: "Bomba Submersa Leão 3\" 180 3R3PB-18 1 CV 220v",
    slug: "bomba-submersa-leao-3r3pb-18-180",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-07 0,33 CV 220V</p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-07<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,33 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 07<br />\r\nTensão: 220 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 40 mca<br />\r\nVazão </p>\r\n\r\n<p>40 mts - 1000 L/H</p>\r\n\r\n<p>24 mts - 2500 L/H</p>\r\n\r\n<p>1,3 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "3R3PB-18-180",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/31094486/2-4uxl9tqnvi.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/31094486/2-4uxl9tqnvi.png"],
    specs: [{ spec_name: "Potência", spec_value: "1 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-5",
    name: "Bomba Submersa Leão 4\" 230 4R4PA-08 0,75 CV 220V",
    slug: "bomba-submersa-leao-4r4pa-08-230",
    short_description: null,
    description: "<p>Bomba Submersa Leão 4 Polegadas 230 4R3PA-11 1 CV 220V</p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R3PA-11</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 1 CV</p>\r\n\r\n<p>Tensão: 220V MONO e 220V TRIF</p>\r\n\r\n<p>Amperagem: 4.8 A e 2.7</p>\r\n\r\n<p>Profundidade Max: 102 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">102 Metros - 600 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">85 Metros - 2100 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">38 Metros - 3600 L/h</p>\r\n\r\n<p><span style=\"font-size:14px;\">Bocal de saída 1 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R4PA-08-230-220",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/31093959/2-7m4cvjykpr.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/31093959/2-7m4cvjykpr.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,75 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-6",
    name: "Bomba Submersa Leão 3\" 180 3R3PB-09 0,5 CV 220v",
    slug: "bomba-submersa-leao-3r3pb-09-180",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-07 0,33 CV 220V</p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-07<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,33 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 07<br />\r\nTensão: 220 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 40 mca<br />\r\nVazão </p>\r\n\r\n<p>40 mts - 1000 L/H</p>\r\n\r\n<p>24 mts - 2500 L/H</p>\r\n\r\n<p>1,3 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "3R3PB-09-180",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26743630/2-9hbvaqnasz.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26743630/2-9hbvaqnasz.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,5 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-7",
    name: "Bomba Submersa Leão 3\" 180 3R3PB-13 3/4cv",
    slug: "bomba-submersa-leao-3r3pb-13-180",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-07 0,33 CV 220V</p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-07<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,33 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 07<br />\r\nTensão: 220 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 40 mca<br />\r\nVazão </p>\r\n\r\n<p>40 mts - 1000 L/H</p>\r\n\r\n<p>24 mts - 2500 L/H</p>\r\n\r\n<p>1,3 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "3R3PB-13-180",
    price: 900,
    show_price: true,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26741384/2-gnmkpduq3q.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26741384/2-gnmkpduq3q.png"],
    specs: [{ spec_name: "Potência", spec_value: "4 CV" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-8",
    name: "Bomba submersa vibratória - Anauger 6\"",
    slug: "bomba-submersa-vibratoria-anauger-6",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-07 0,33 CV 220V</p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-07<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,33 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 07<br />\r\nTensão: 220 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 40 mca<br />\r\nVazão </p>\r\n\r\n<p>40 mts - 1000 L/H</p>\r\n\r\n<p>24 mts - 2500 L/H</p>\r\n\r\n<p>1,3 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-1",
    sku: "2Z6R55R89",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26665331/1-ewdx48icjz.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26665331/1-ewdx48icjz.png"],
    specs: [{ spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-9",
    name: "Bomba Submersa Leão 4\" 230 4R5PA-12 2 CV 220v",
    slug: "bomba-submersa-leao-4r5pa-12-230",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 4\" 230 4R5PA-18 3CV 220v</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R5PA-18</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 3CV</p>\r\n\r\n<p>Tensão: 220V TRIF</p>\r\n\r\n<p>Amperagem:  10,3 A</p>\r\n\r\n<p>Profundidade Max: 167 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">167 Metros - 1500 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">128 Metros - 4000 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">62 Metros - 6500 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"box-sizing: border-box; padding: 0px; margin: 0px 0px 12px; font-size: 16px; direction: ltr; list-style: square; line-height: 1.3em;box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\"><span style=\"font-size:14px;\"> Bocal de saída 1 1/2” com rosca BSP;</span></span></p>\r\n\r\n<p><span style=\"font-size:14px;\">Especificações de acoplagem conforme a Norma NEMA;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R5PA-12-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26544531/3-0n4i0kzk6u.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26544531/3-0n4i0kzk6u.png"],
    specs: [{ spec_name: "Potência", spec_value: "2 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-10",
    name: "Bomba Submersa Leão 4\" 230 4R5PA-09 1,5 CV",
    slug: "bomba-submersa-leao-4r5pa-09-230",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 4\" 370 4R5PA-09 1,5 CV 220V</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R5PA-09</p>\r\n\r\n<p>Serie motor: 370 (Água)</p>\r\n\r\n<p>Potência: 1,5 CV</p>\r\n\r\n<p>Tensão: 220V TRIF</p>\r\n\r\n<p>Amperagem: 7,3A</p>\r\n\r\n<p>Profundidade Max: 89 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">89 Metros - 1500 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">68 Metros - 4000 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">35 Metros - 6500 L/h</p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R5PA-09-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26543982/1-9jaz3hjjia.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26543982/1-9jaz3hjjia.png"],
    specs: [{ spec_name: "Potência", spec_value: "1,5 CV" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-11",
    name: "Bomba Submersa Leão 4\" 230 4R4PA-10 1,0 CV 220v",
    slug: "bomba-submersa-leao-4r4pa-10-230",
    short_description: null,
    description: "<p>Bomba Submersa Leão 4 Polegadas 230 4R3PA-11 1 CV 220V</p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R3PA-11</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 1 CV</p>\r\n\r\n<p>Tensão: 220V MONO e 220V TRIF</p>\r\n\r\n<p>Amperagem: 4.8 A e 2.7</p>\r\n\r\n<p>Profundidade Max: 102 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">102 Metros - 600 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">85 Metros - 2100 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">38 Metros - 3600 L/h</p>\r\n\r\n<p><span style=\"font-size:14px;\">Bocal de saída 1 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R4PA-10-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26542654/2-x1vgn5lu89.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26542654/2-x1vgn5lu89.png"],
    specs: [{ spec_name: "Potência", spec_value: "1,0 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-12",
    name: "Bomba Submersa Leão 4\" 230 4R3PA-07 0,5 CV 220V",
    slug: "bomba-submersa-leao-4r3pa-07-230",
    short_description: null,
    description: "<p>Bomba Submersa Leão 4 Polegadas 230 4R3PA-11 1 CV 220V</p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R3PA-11</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 1 CV</p>\r\n\r\n<p>Tensão: 220V MONO e 220V TRIF</p>\r\n\r\n<p>Amperagem: 4.8 A e 2.7</p>\r\n\r\n<p>Profundidade Max: 102 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">102 Metros - 600 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">85 Metros - 2100 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">38 Metros - 3600 L/h</p>\r\n\r\n<p><span style=\"font-size:14px;\">Bocal de saída 1 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R3PA-07-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26516433/2-qz1c8jk38q.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26516433/2-qz1c8jk38q.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,5 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-13",
    name: "Bomba Submersa Leão 4\" 230 4R5PA-18 3CV 220v",
    slug: "bomba-submersa-leao-4r5pa-18-230",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 4\" 230 4R5PA-18 3CV 220v</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R5PA-18</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 3CV</p>\r\n\r\n<p>Tensão: 220V TRIF</p>\r\n\r\n<p>Amperagem:  10,3 A</p>\r\n\r\n<p>Profundidade Max: 167 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">167 Metros - 1500 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">128 Metros - 4000 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">62 Metros - 6500 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"box-sizing: border-box; padding: 0px; margin: 0px 0px 12px; font-size: 16px; direction: ltr; list-style: square; line-height: 1.3em;box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\"><span style=\"font-size:14px;\"> Bocal de saída 1 1/2” com rosca BSP;</span></span></p>\r\n\r\n<p><span style=\"font-size:14px;\">Especificações de acoplagem conforme a Norma NEMA;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R5PA-18-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/226000907/4r1-4r3r-4r3-4r4-4r5_gallery-r6wfj20b5p.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/226000907/4r1-4r3r-4r3-4r4-4r5_gallery-r6wfj20b5p.png"],
    specs: [{ spec_name: "Potência", spec_value: "3 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-14",
    name: "Bomba Submersa Leão 4\" 370 4R5PA-12 2CV",
    slug: "bomba-submersa-leao-4r5pa-12-370",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 4\" 370 4R5PA-12 2CV 220V</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R5PA-12</p>\r\n\r\n<p>Serie motor: 370 (Água)</p>\r\n\r\n<p>Potência: 2 CV</p>\r\n\r\n<p>Tensão: 220V TRIF</p>\r\n\r\n<p>Amperagem: 8,3A</p>\r\n\r\n<p>Profundidade Max: 117 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">117 Metros - 1500 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">91 Metros - 4000 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">48 Metros - 6500 L/h</p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R5PA-12-370",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225999291/4r1-4r3r-4r3-4r4-4r5_gallery-z9bb9veyjx.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225999291/4r1-4r3r-4r3-4r4-4r5_gallery-z9bb9veyjx.png"],
    specs: [{ spec_name: "Potência", spec_value: "2 CV" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-15",
    name: "Bomba Submersa Leão 4\" 370 4R5PA-09 1,5 CV",
    slug: "bomba-submersa-leao-4r5pa-09-370",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 4\" 370 4R5PA-12 2CV 220V</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R5PA-12</p>\r\n\r\n<p>Serie motor: 370 (Água)</p>\r\n\r\n<p>Potência: 2 CV</p>\r\n\r\n<p>Tensão: 220V TRIF</p>\r\n\r\n<p>Amperagem: 8,3A</p>\r\n\r\n<p>Profundidade Max: 117 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">117 Metros - 1500 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">91 Metros - 4000 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">48 Metros - 6500 L/h</p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R5PA-09-370",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225997832/4r1-4r3r-4r3-4r4-4r5_gallery-34wlk4i9i1.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225997832/4r1-4r3r-4r3-4r4-4r5_gallery-34wlk4i9i1.png"],
    specs: [{ spec_name: "Potência", spec_value: "1,5 CV" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-16",
    name: "Bomba Submersa Leão 6\" R20A-08 8CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r20a-08-610",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R20A-09 9CV 220/380 TRIF S600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R20A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 9CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 28A / 16,41A</p>\r\n\r\n<p>Profundidade Max: 128 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">128 Metros - 12.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">104 Metros - 18.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">66 Metros - 24.000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R20A-08-610",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225923348/r7-r11-r20-r28-s610-fvh6ci6ygj.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225923348/r7-r11-r20-r28-s610-fvh6ci6ygj.jpg"],
    specs: [{ spec_name: "Potência", spec_value: "8 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-17",
    name: "Bomba Submersa Leão 6\" R20A-09 9CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r20a-09-600",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R20A-08 8CV 220/380 TRIF S600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R20A-08</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 8CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 23,5A / 13,6A</p>\r\n\r\n<p>Profundidade Max: 115 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">115 Metros - 12.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">94 Metros - 18.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">60,5 Metros - 24.000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R20A-09-600",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225922607/r7a-r11a-r20a-r28a-motor-600_site_product-ox5vffrb8f.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225922607/r7a-r11a-r20a-r28a-motor-600_site_product-ox5vffrb8f.png"],
    specs: [{ spec_name: "Potência", spec_value: "9 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-18",
    name: "Bomba Submersa Leão 6\" R20A-7 7CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r20a-07-600",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R20A-09 9CV 220/380 TRIF S600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R20A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 9CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 28A / 16,41A</p>\r\n\r\n<p>Profundidade Max: 128 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">128 Metros - 12.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">104 Metros - 18.000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">66 Metros - 24.000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R20A-07-600",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225920101/r7a-r11a-r20a-r28a-motor-600_site_product-pcv5fqpe62.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225920101/r7a-r11a-r20a-r28a-motor-600_site_product-pcv5fqpe62.png"],
    specs: [{ spec_name: "Potência", spec_value: "7 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-19",
    name: "Bomba Submersa Leão 6\" R11A-11 7CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r11a-11-500",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R11A-09 6CV 220/380 TRIF s600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R11A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 6CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 19,73A / 11,59A</p>\r\n\r\n<p>Profundidade Max: 120 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">120 Metros - 6000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">103 Metros - 10000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">72 Metros - 14000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R11A-11-500",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225917485/r7-r11-r20-r28-s610-7se7xk7rrv.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225917485/r7-r11-r20-r28-s610-7se7xk7rrv.jpg"],
    specs: [{ spec_name: "Potência", spec_value: "7 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-20",
    name: "Bomba Submersa Leão 6\" R11A-14 9CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r11a-14-610",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R11A-09 6CV 220/380 TRIF s600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R11A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 6CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 19,73A / 11,59A</p>\r\n\r\n<p>Profundidade Max: 120 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">120 Metros - 6000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">103 Metros - 10000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">72 Metros - 14000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R11A-14-610",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225909785/r7-r11-r20-r28-s610-hpxotwy9ns.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225909785/r7-r11-r20-r28-s610-hpxotwy9ns.jpg"],
    specs: [{ spec_name: "Potência", spec_value: "9 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-21",
    name: "Bomba Submersa Leão 6\" R11A-10 6,5CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r11a-10-600",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R11A-09 6CV 220/380 TRIF s600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R11A-09</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 6CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 19,73A / 11,59A</p>\r\n\r\n<p>Profundidade Max: 120 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">120 Metros - 6000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">103 Metros - 10000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">72 Metros - 14000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R11A-10-600",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225905124/r7a-r11a-r20a-r28a-motor-600_site_product-55dt7q3ivf.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225905124/r7a-r11a-r20a-r28a-motor-600_site_product-55dt7q3ivf.png"],
    specs: [{ spec_name: "Potência", spec_value: "6,5 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-22",
    name: "Bomba Submersa Leão 6\" R11A-09 6CV 220/380V TRI S600",
    slug: "bomba-submersa-leao-r11a-09-600",
    short_description: null,
    description: "<p><strong>Bomba Submersa Leão 6\" R11A-10 6,5CV 220/380 TRIF s600</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 6”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: R11A-10</p>\r\n\r\n<p>Serie Motor: 600 (Água)</p>\r\n\r\n<p>Potência: 6,5CV</p>\r\n\r\n<p>Tensão: 220/380V TRIF</p>\r\n\r\n<p>Amperagem: 20,72A / 12,14A</p>\r\n\r\n<p>Profundidade Max: 133 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left: 54pt;\">133 Metros - 6000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">113 Metros - 10000 L/h</p>\r\n\r\n<p style=\"margin-left: 54pt;\">80 Metros - 14000 L/h</p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Acoplagem por sistema de chaveta;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Rotor de fluxo radial;</span></p>\r\n\r\n<p><span class=\"indent0\" style=\"direction: ltr; list-style: square; line-height: 1.3em; box-sizing: border-box; padding: 0px; margin: 0px 0px 0px -4px; display: block;\">Bocal de saída 2” com rosca BSP;</span></p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo de estágio, mancal superior/intermediário e corpo da válvula de retenção de ferro fundido, rotor e eixo em inox.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "R11A-09-600",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225902555/r7a-r11a-r20a-r28a-motor-600_site_product-tj6dm7kwm3.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225902555/r7a-r11a-r20a-r28a-motor-600_site_product-tj6dm7kwm3.png"],
    specs: [{ spec_name: "Potência", spec_value: "6 CV" }, { spec_name: "Tensão", spec_value: "220/380V" }, { spec_name: "Diâmetro do poço", spec_value: "6\"" }],
    variations: [],
  },
  {
    id: "prod-23",
    name: "Bomba Submersa Leão 4\" 230 4R3PA-11 1 CV 220V",
    slug: "bomba-submersa-leao-4r3pa-11-230",
    short_description: null,
    description: "<p>Bomba Submersa Leão 4 Polegadas 230 4R3PA-11 1 CV 220V</p>\r\n\r\n<p> </p>\r\n\r\n<p><strong>--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p>Motores projetados para operar acoplado em bombas para captação de águas subterrâneas em poços com diâmetro interno mínimo de 4”;</p>\r\n\r\n<p>Suas principais aplicações são sistemas de abastecimento público, industrial, agrícola, irrigação e mineração;</p>\r\n\r\n<p>Pressurização em rede hidráulica;</p>\r\n\r\n<p>Reservatórios.</p>\r\n\r\n<p><strong>--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo: 4R3PA-11</p>\r\n\r\n<p>Serie motor: 230 (Óleo)</p>\r\n\r\n<p>Potência: 1 CV</p>\r\n\r\n<p>Tensão: 220V MONO e 220V TRIF</p>\r\n\r\n<p>Amperagem: 4.8 A e 2.7</p>\r\n\r\n<p>Profundidade Max: 102 Metros</p>\r\n\r\n<p>Tabela de Curva - Vazão</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">102 Metros - 600 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">85 Metros - 2100 L/h</p>\r\n\r\n<p style=\"margin-left:54.0pt;\">38 Metros - 3600 L/h</p>\r\n\r\n<p><span style=\"font-size:14px;\">Bocal de saída 1 1/2” com rosca BSP;</span></p>\r\n\r\n<p>Especificações de acoplagem conforme a Norma NEMA;</p>\r\n\r\n<p>Máximo de 10 partidas por hora com intervalo de 6 minutos a cada partida;</p>\r\n\r\n<p>Temperatura máxima de operação: 40°C</p>\r\n\r\n<p>Bombeador é composto por: corpo de sucção, corpo da válvula de retenção, difusor e rotor de tecnopolímero injetado.</p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>",
    category_id: "cat-1",
    brand_id: "brand-2",
    sku: "4R3PA-11-230",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225861853/inox-4r1-r3-r3r-r4-r5ia_r3-e-r5ib-sem-fio_gallery-aql1v8xr2j.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225861853/inox-4r1-r3-r3r-r4-r5ia_r3-e-r5ib-sem-fio_gallery-aql1v8xr2j.jpg"],
    specs: [{ spec_name: "Potência", spec_value: "1 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "4\"" }],
    variations: [],
  },
  {
    id: "prod-24",
    name: "Bomba Submersa Ebara 3\" 3BPS2-14 0,75 CV",
    slug: "bomba-submersa-ebara-3bps2-14",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-14 0,75 CV </p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-14<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,75 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 14<br />\r\nTensão: 127 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 80 mca<br />\r\nVazão </p>\r\n\r\n<p>80 mts - 1000 L/H</p>\r\n\r\n<p>44 mts - 2500 L/H</p>\r\n\r\n<p>1,4 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-4",
    sku: "3BPS2-14",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225859691/1-37k8929o8w.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225859691/1-37k8929o8w.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,75 CV" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-25",
    name: "Bomba Submersa Ebara 3\" 3BPS2-10 0,50 CV",
    slug: "bomba-submersa-ebara-3bps2-10",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-14 0,75 CV </p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-14<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,75 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 14<br />\r\nTensão: 127 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 80 mca<br />\r\nVazão </p>\r\n\r\n<p>80 mts - 1000 L/H</p>\r\n\r\n<p>44 mts - 2500 L/H</p>\r\n\r\n<p>1,4 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-4",
    sku: "3BPS2-10",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225857415/1-p00y2ye2jn.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225857415/1-p00y2ye2jn.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,50 CV" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-26",
    name: "Bomba Submersa Ebara 3\" 3BPS2-07 0,33 CV 220V",
    slug: "bomba-submersa-ebara-3bps2-07",
    short_description: null,
    description: "<p>Bomba Submersa Ebara 3\" 3BPS2-10 0,50 CV </p>\r\n\r\n<p>Aplicações:</p>\r\n\r\n<p>Captação de água potável em poços tubulares profundos;<br />\r\nFornecimento de água para uso residencial, industrial e agrícola;<br />\r\nReservatórios.</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo: 3BPS2-10<br />\r\nMarca:Ebara<br />\r\nPotencia: 0,50 cv<br />\r\nSerie do Motor: M3C <br />\r\nEstágios: 10<br />\r\nTensão: 127 V 2 FIOS<br />\r\nFase: Monofásica<br />\r\nAltura Manométrica Máxima: 57 mca<br />\r\nVazão </p>\r\n\r\n<p>57 mts - 1000 L/H</p>\r\n\r\n<p>33 mts - 2500 L/H</p>\r\n\r\n<p>1,8 mts - 3800 L/H</p>\r\n\r\n<p>Recalque: 1\"</p>\r\n\r\n<p>Diâmetro: 3\" (75mm)<br />\r\n </p>\r\n\r\n<p><strong>--OBSERVAÇÕES</strong></p>\r\n\r\n<p>O equipamento não deve trabalhar sem água.</p>\r\n\r\n<p>As vazões acima descritas correspondem aos respectivos níveis dinâmicos e não ao ponto de instalação da bomba. Portanto, quando se basear pelo ponto de instalação, as vazões serão MAIORES que as descritas, considerando que o poço consiga produzir a quantidade de água extraída.<br />\r\n<br />\r\nNível dinâmico: Nível de água do poço com a bomba ligada.</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-1",
    brand_id: "brand-4",
    sku: "3BPS2-07",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225152806/1-yfluxqk532.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225152806/1-yfluxqk532.png"],
    specs: [{ spec_name: "Potência", spec_value: "0,33 CV" }, { spec_name: "Tensão", spec_value: "220V" }, { spec_name: "Diâmetro do poço", spec_value: "3\"" }],
    variations: [],
  },
  {
    id: "prod-27",
    name: "Bomba Drenagem Schneider LUP-05",
    slug: "bomba-drenagem-schneider-lup-05",
    short_description: null,
    description: "<p>Aplicações Gerais</p>\r\n\r\n<p>• Aplicações residenciais</p>\r\n\r\n<p>• Limpeza de caixas d’água, poços, reservatórios e cisternas</p>\r\n\r\n<p>• Drenagem de pequenas piscinas, porões e garagens Detalhes Técnicos</p>\r\n\r\n<p>• Bocal com rosca BSP e com adaptador para mangueira</p>\r\n\r\n<p>• Corpo da motobomba em polipropileno • Caracol de polipropileno com 20% de fibra de vidro</p>\r\n\r\n<p>• Rotor de poliamida com 30% de fibra de vidro</p>\r\n\r\n<p>• Selo mecânico constituído de aço inox AISI-304, buna N, grafite e cerâmica</p>\r\n\r\n<p>• Motor elétrico IP-68 com protetor térmico, 2 Polos, 60 Hz, Monofásico</p>\r\n\r\n<p>• Tensão: 127 V ou 220 V • Comprimento do cabo de ligação: 5 metros</p>\r\n\r\n<p>Características:</p>\r\n\r\n<p>Modelo:LUP-05<br />\r\nMarca: SCHNEIDER<br />\r\nPotencia: 0,5 cv<br />\r\nTensão: 127V 220 V <br />\r\nFase: Monofásica<br />\r\nAltura Manometrica Máxima: 7 mca<br />\r\nVazão Máxima: 8,2 m/h<br />\r\nRecalque:  1 1/4\" ou 1”<br />\r\nPeso: Aprox. 7,7 kg<br />\r\nRotor de fluxo radial</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>\r\n\r\n<p>Importante</p>\r\n\r\n<p>•  Temperatura máxima do líquido bombeado: 40 °C</p>\r\n\r\n<p>• Profundidade de imersão máxima: 7 metros</p>",
    category_id: "cat-2",
    brand_id: "brand-8",
    sku: "LUP-05",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225013642/2-hj5cd3u6z5.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225013642/2-hj5cd3u6z5.png"],
    specs: [{ spec_name: "Aplicação", spec_value: "Drenagem de água limpa/levemente suja" }],
    variations: [],
  },
  {
    id: "prod-28",
    name: "Cabo Pp Flexível 3x6mm Condumig",
    slug: "cabo-pp-flexivel-3x6mm-condumig",
    short_description: null,
    description: "<p><strong>Cabo PP Flexível 2x2.5mm Condumig</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p>Cabo de potência, com condutor flexível - Cobre; HEPR 90 °C  </p>\r\n\r\n<p>Tensão Nominal: 0,6/1kV – Classe 4;  </p>\r\n\r\n<p>2 vias de 2.5mm</p>\r\n\r\n<p>Flexível</p>\r\n\r\n<p>Normas Técnicas / Regulamento: NBR 7286:2015.</p>\r\n\r\n<p><br />\r\nExcelente para ligação de bombas submersas, máquinas, fazer extensões. Etc...<br />\r\n  </p>\r\n\r\n<p>Marca Condumig</p>",
    category_id: "cat-3",
    brand_id: "brand-3",
    sku: "CABO3X6",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225245249/1-2fcx6gnk0p.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225245249/1-2fcx6gnk0p.png"],
    specs: [{ spec_name: "Bitola", spec_value: "3x6mm²" }],
    variations: [{ id: "vg-prod-28-1", name: "Metros", options: [{ id: "vo-prod-28-1-1", value: "10 MTS", price_delta: 0 }, { id: "vo-prod-28-1-2", value: "20 MTS", price_delta: 0 }, { id: "vo-prod-28-1-3", value: "50 MTS", price_delta: 0 }, { id: "vo-prod-28-1-4", value: "60 MTS", price_delta: 0 }, { id: "vo-prod-28-1-5", value: "80 MTS", price_delta: 0 }, { id: "vo-prod-28-1-6", value: "100 MTS", price_delta: 0 }] }],
  },
  {
    id: "prod-29",
    name: "Cabo Pp Flexível 3x4mm Condumig",
    slug: "cabo-pp-flexivel-3x4mm-condumig",
    short_description: null,
    description: "<p><strong>Cabo PP Flexível 3x6mm Condumig</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p>Cabo de potência, com condutor flexível - Cobre; HEPR 90 °C  </p>\r\n\r\n<p>Tensão Nominal: 0,6/1kV – Classe 4;  </p>\r\n\r\n<p>3 vias de 6mm</p>\r\n\r\n<p>Flexível</p>\r\n\r\n<p>Normas Técnicas / Regulamento: NBR 7286:2015.</p>\r\n\r\n<p><br />\r\nExcelente para ligação de bombas submersas, máquinas, fazer extensões. Etc...<br />\r\n  </p>\r\n\r\n<p>Marca Condumig</p>",
    category_id: "cat-3",
    brand_id: "brand-3",
    sku: "CABO3X4",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225243370/1-thr4mdivuk.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225243370/1-thr4mdivuk.png"],
    specs: [{ spec_name: "Bitola", spec_value: "3x4mm²" }],
    variations: [{ id: "vg-prod-29-1", name: "Metros", options: [{ id: "vo-prod-29-1-1", value: "10 MTS", price_delta: 0 }, { id: "vo-prod-29-1-2", value: "20 MTS", price_delta: 0 }, { id: "vo-prod-29-1-3", value: "50 MTS", price_delta: 0 }, { id: "vo-prod-29-1-4", value: "60 MTS", price_delta: 0 }, { id: "vo-prod-29-1-5", value: "80 MTS", price_delta: 0 }, { id: "vo-prod-29-1-6", value: "100 MTS", price_delta: 0 }] }],
  },
  {
    id: "prod-30",
    name: "Cabo Pp Flexível 3x2.5mm Condumig",
    slug: "cabo-pp-flexivel-3x2-5mm-condumig",
    short_description: null,
    description: "<p><strong>Cabo PP Flexível 2x2.5mm Condumig</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p>Cabo de potência, com condutor flexível - Cobre; HEPR 90 °C  </p>\r\n\r\n<p>Tensão Nominal: 0,6/1kV – Classe 4;  </p>\r\n\r\n<p>2 vias de 2.5mm</p>\r\n\r\n<p>Flexível</p>\r\n\r\n<p>Normas Técnicas / Regulamento: NBR 7286:2015.</p>\r\n\r\n<p><br />\r\nExcelente para ligação de bombas submersas, máquinas, fazer extensões. Etc...<br />\r\n  </p>\r\n\r\n<p>Marca Condumig</p>",
    category_id: "cat-3",
    brand_id: "brand-3",
    sku: "CABO3X2-5",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225106885/3-v1spwveaji.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225106885/3-v1spwveaji.png"],
    specs: [{ spec_name: "Bitola", spec_value: "3x2,5mm²" }],
    variations: [{ id: "vg-prod-30-1", name: "Metros", options: [{ id: "vo-prod-30-1-1", value: "10 MTS", price_delta: 0 }, { id: "vo-prod-30-1-2", value: "20 MTS", price_delta: 0 }, { id: "vo-prod-30-1-3", value: "50 MTS", price_delta: 0 }, { id: "vo-prod-30-1-4", value: "60 MTS", price_delta: 0 }, { id: "vo-prod-30-1-5", value: "80 MTS", price_delta: 0 }, { id: "vo-prod-30-1-6", value: "100 MTS", price_delta: 0 }] }],
  },
  {
    id: "prod-31",
    name: "Cabo Pp Flexível 2x2.5mm Condumig",
    slug: "cabo-pp-flexivel-2x2-5mm-condumig",
    short_description: null,
    description: "<p><strong>Cabo PP Flexível 2x2.5mm Condumig</strong></p>\r\n\r\n<p> </p>\r\n\r\n<p>Cabo de potência, com condutor flexível - Cobre; HEPR 90 °C  </p>\r\n\r\n<p>Tensão Nominal: 0,6/1kV – Classe 4;  </p>\r\n\r\n<p>2 vias de 2.5mm</p>\r\n\r\n<p>Flexível</p>\r\n\r\n<p>Normas Técnicas / Regulamento: NBR 7286:2015.</p>\r\n\r\n<p><br />\r\nExcelente para ligação de bombas submersas, máquinas, fazer extensões. Etc...<br />\r\n  </p>\r\n\r\n<p>Marca Condumig</p>",
    category_id: "cat-3",
    brand_id: "brand-3",
    sku: "CABO2X2-5",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225104097/3-ctexl3sou8.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225104097/3-ctexl3sou8.png"],
    specs: [{ spec_name: "Bitola", spec_value: "2x2,5mm²" }],
    variations: [{ id: "vg-prod-31-1", name: "Metros", options: [{ id: "vo-prod-31-1-1", value: "10 MTS", price_delta: 0 }, { id: "vo-prod-31-1-2", value: "20 MTS", price_delta: 0 }, { id: "vo-prod-31-1-3", value: "50 MTS", price_delta: 0 }, { id: "vo-prod-31-1-4", value: "60 MTS", price_delta: 0 }, { id: "vo-prod-31-1-5", value: "80 MTS", price_delta: 0 }, { id: "vo-prod-31-1-6", value: "100 MTS", price_delta: 0 }] }],
  },
  {
    id: "prod-32",
    name: "Luva Galvanizada TUPY",
    slug: "luva-galvanizada-tupy",
    short_description: null,
    description: "<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><strong style=\"margin: 0px; padding: 0px;\">--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><span style=\"color: rgb(85, 85, 85); font-family: Lato, sans-serif;\">As conexões NPT-Média Pressão são aplicadas para a condução de líquidos, gases e vapores.</span></p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"> </p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><strong style=\"margin: 0px; padding: 0px;\">--DETALHES DO PRODUTO</strong></p>\r\n\r\n<table border=\"0\" style=\"box-sizing: border-box; border-collapse: collapse; border-spacing: 0px; background: rgb(158, 158, 158); width: 1012px; border: 1px solid rgb(209, 209, 209); color: rgb(85, 85, 85); font-family: Lato, sans-serif; outline: none !important;\">\r\n\t<thead style=\"box-sizing: border-box;\">\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<th colspan=\"2\" style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">Diâmetro nominal</th>\r\n\t\t\t<th colspan=\"1\" style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">Dimensões em mm</th>\r\n\t\t\t<th rowspan=\"2\" style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">Peso em g</th>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<th style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">Polegada</th>\r\n\t\t\t<th style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">mm</th>\r\n\t\t\t<th style=\"box-sizing: border-box; padding: 5px 8px; text-align: left; font-weight: 400; color: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209);\">W</th>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody style=\"box-sizing: border-box;\">\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">1/4\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">8mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">26,9</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">49</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">1/2\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">15mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">34</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">91</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">3/4\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">20mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">38,6</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">156</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">1\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">25mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">42,4</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">226</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">1.1/4\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">32mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">49</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">352</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">1.1/2\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">40mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">54,6</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">448</td>\r\n\t\t</tr>\r\n\t\t<tr style=\"box-sizing: border-box;\">\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">2\"</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">50mm</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">64,3</td>\r\n\t\t\t<td style=\"box-sizing: border-box; padding: 7px 8px; background: rgb(255, 255, 255); border: 1px solid rgb(209, 209, 209); border-collapse: collapse;\">737</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<p> </p>",
    category_id: "cat-4",
    brand_id: "brand-9",
    sku: "LUVA",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26544772/612cdd50a15a7-k7wcfkztwk.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26544772/612cdd50a15a7-k7wcfkztwk.jpg"],
    specs: [{ spec_name: "Material", spec_value: "Ferro galvanizado" }],
    variations: [],
  },
  {
    id: "prod-33",
    name: "Abraçadeira Metal Reforçada P/ Mangueira",
    slug: "abracadeira-metal-reforcada-p-mangueira",
    short_description: null,
    description: "<p>Abraçadeira Reforçada para Mangueira Fundição Medeiros </p>\r\n\r\n<p><strong>Indicação:</strong></p>\r\n\r\n<p>— Mangueiras de material rígido em altas pressões;</p>\r\n\r\n<p><strong>Medidas:</strong></p>\r\n\r\n<p><strong>1\" 29mm x 32mm</strong></p>\r\n\r\n<p>— POLEGADAS: Mínima 1 1/8\" Máxima 1 1/4\"<br />\r\n— MILÍMETROS: Mínima 29mm Máxima 32mm</p>\r\n\r\n<p><strong>1 1/4\" 32mm x 40mm </strong></p>\r\n\r\n<p>— POLEGADAS: Mínima 1 3/8\" Máxima 1 1/2\"<br />\r\n— MILÍMETROS: Mínima 32mm Máxima 40mm</p>\r\n\r\n<p><strong>1 1/2\" 39mm x 47mm Fundição Medeiros 2 peças</strong></p>\r\n\r\n<p>— POLEGADAS: Mínima 1 1/2\" Máxima 1 7/8\"<br />\r\n— MILÍMETROS: Mínima 39mm Máxima 47mm</p>\r\n\r\n<p><strong>Material:</strong></p>\r\n\r\n<p>— Aço zincado;</p>\r\n\r\n<p> </p>\r\n\r\n<p> </p>",
    category_id: "cat-4",
    brand_id: "brand-5",
    sku: "ABRA-FM",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225211398/1-dxh10l1i19.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225211398/1-dxh10l1i19.png"],
    specs: [{ spec_name: "Material", spec_value: "Metal reforçado" }],
    variations: [],
  },
  {
    id: "prod-34",
    name: "Adaptado P/ Mangueira Macho Escama x Bsp - Ferro Fundido",
    slug: "adaptado-p-mangueira-macho-escama-bsp-ferro-fundido",
    short_description: null,
    description: "<p>Adaptado P/ Mangueira Macho Escama x Rosca BSP - Ferro Fundido </p>\r\n\r\n<p>Medidas:</p>\r\n\r\n<p><strong>1\" Escama x 1\" Rosca BSP:</strong></p>\r\n\r\n<p>- Comprimento: 72mm</p>\r\n\r\n<p>- Escama: 27mm</p>\r\n\r\n<p>- Rosca BSP: 1\"</p>\r\n\r\n<p><strong>1 1/4\" Escama x 1 1/4\" Rosca BSP:</strong></p>\r\n\r\n<p>- Comprimento: 78mm</p>\r\n\r\n<p>- Escama: 36mm</p>\r\n\r\n<p>- Rosca BSP: 1 1/4\"</p>\r\n\r\n<p><strong>1 1/2\" Escama x 1 1/4\" Rosca BSP:</strong></p>\r\n\r\n<p>- Comprimento: 85mm</p>\r\n\r\n<p>- Escama: 41mm</p>\r\n\r\n<p>- Rosca BSP: 1 1/2\"</p>\r\n\r\n<p> </p>",
    category_id: "cat-4",
    brand_id: "brand-5",
    sku: "ADAP-MAG-FM",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225205950/1-9mqj4b3ixb.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225205950/1-9mqj4b3ixb.png"],
    specs: [{ spec_name: "Material", spec_value: "Ferro fundido" }],
    variations: [],
  },
  {
    id: "prod-35",
    name: "Válvula Esfera Monobloco em Latão Niquelado - Mipel",
    slug: "valvula-esfera-monobloco-latao-niquelado-mipel",
    short_description: null,
    description: "<p>REGISTRO ESFERA MIPEL METAL  BSP</p>\r\n\r\n<p>Válvula de Esfera Monobloco em Latão Niquelado</p>\r\n\r\n<p> </p>\r\n\r\n<p>Bitola: 1.1/4\" (passagem plena)</p>\r\n\r\n<p>Bitola: 1.1/2\" (passagem plena) DN 40</p>\r\n\r\n<p> </p>\r\n\r\n<p>Pressão de Trabalho: PN 30 435 psi</p>\r\n\r\n<p>Temperatura de Trabalho: -10° à 90°C</p>\r\n\r\n<p>Extremidade: BSP (ISO 228-1/228-2)</p>\r\n\r\n<p>Aplicação: Água, Óleo e Ar </p>\r\n\r\n<p>Materiais:<br />\r\nCorpo/Tampa: Latão Niquelado;<br />\r\nEsfera/Haste: Latão Niquelado;<br />\r\nVedações: PTFE.</p>",
    category_id: "cat-4",
    brand_id: "brand-7",
    sku: "REG-ESF-MIPEL",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225204544/9101i3e-ng23ukmra8.jpg",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225204544/9101i3e-ng23ukmra8.jpg"],
    specs: [{ spec_name: "Material", spec_value: "Latão niquelado" }],
    variations: [],
  },
  {
    id: "prod-36",
    name: "Painel de Comando Completo Trifásico 220V",
    slug: "painel-comando-completo-trifasico-220v",
    short_description: null,
    description: "<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><strong style=\"margin: 0px; padding: 0px;\">--APLICAÇÕES GERAIS</strong></p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><span style=\"color: rgb(34, 34, 34); font-family: &quot;Gotham XNarrow SSm A&quot;, &quot;Gotham XNarrow SSm B&quot;, &quot;Arial Narrow&quot;, Arial; font-size: 16px;\">Utilizados para partida de motores elétricos submersíveis com tensões monofásicas ou trifásicas.</span></p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><strong style=\"margin: 0px; padding: 0px;\">--DETALHES DO PRODUTO</strong></p>\r\n\r\n<p>Modelo : Trifásico Completo<br />\r\nPotência : Até 4 CV <br />\r\nTensão : 220V</p>\r\n\r\n<p><span style=\"color: rgb(34, 34, 34); font-family: &quot;Gotham XNarrow SSm A&quot;, &quot;Gotham XNarrow SSm B&quot;, &quot;Arial Narrow&quot;, Arial; font-size: 16px;\">Armário de aço, disjuntores, contatores, reles de sobrecarga, chave automático-manual, bornes para boia, amperímetro, voltímetro, sinaleiro e rele falta de fase;</span></p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"><strong style=\"margin: 0px; padding: 0px;\">--OBSERVAÇÕES</strong></p>\r\n\r\n<p>É preciso escolher a potência desejada</p>\r\n\r\n<p style=\"margin: 0px 0px 10px; padding: 0px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px;\"> </p>",
    category_id: "cat-5",
    brand_id: null,
    sku: "PCCT220V",
    price: null,
    show_price: false,
    is_best_seller: true,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/26929586/1-tqlltj58xd.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/26929586/1-tqlltj58xd.png"],
    specs: [{ spec_name: "Fase", spec_value: "Trifásico" }, { spec_name: "Tensão", spec_value: "220V" }],
    variations: [],
  },
  {
    id: "prod-37",
    name: "Tampa Para Poço Artesiano 6 Polegadas",
    slug: "tampa-poco-artesiano-6-polegadas",
    short_description: null,
    description: "<p>TAMPA PARA POÇO 125mm INTERNO.</p>\r\n\r\n<p>Indicada para POÇOS ARTESIANOS,TUBOS GEOMECÀNICO de 4\" com furo para EDUTOR de 1\" </p>\r\n\r\n<p>MATERIAL: Chapa de aço 5 mm <br />\r\n </p>\r\n\r\n<p>FURO: 1\" MAX 33 mm</p>\r\n\r\n<p>FURO: 1 1/4\" MAX 42 mm</p>\r\n\r\n<p>FURO: 1 1/2\"  MAX 49mm</p>",
    category_id: "cat-6",
    brand_id: "brand-6",
    sku: "TAMPA-6",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225149756/1-q5djty8esp.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225149756/1-q5djty8esp.png"],
    specs: [{ spec_name: "Material", spec_value: "Chapa de aço 5mm" }, { spec_name: "Aplicação", spec_value: "Poços artesianos, tubo geomecânico 6\"" }],
    variations: [{ id: "vg-prod-37-1", name: "Diâmetro nominal", options: [{ id: "vo-prod-37-1-1", value: "6\" X FURO 1 1/4\"", price_delta: 0 }, { id: "vo-prod-37-1-2", value: "6\" X FURO 1\"", price_delta: 0 }] }],
  },
  {
    id: "prod-38",
    name: "Tampa Para Poço Artesiano 4 Polegadas",
    slug: "tampa-poco-artesiano-4-polegadas",
    short_description: null,
    description: "<p>TAMPA PARA POÇO 125mm INTERNO.</p>\r\n\r\n<p>Indicada para POÇOS ARTESIANOS,TUBOS GEOMECÀNICO de 4\" com furo para EDUTOR de 1\" </p>\r\n\r\n<p>MATERIAL: Chapa de aço 5 mm <br />\r\n </p>\r\n\r\n<p>FURO: 1\" MAX 33 mm</p>\r\n\r\n<p>FURO: 1 1/4\" MAX 42 mm</p>\r\n\r\n<p>FURO: 1 1/2\"  MAX 49mm</p>",
    category_id: "cat-6",
    brand_id: "brand-6",
    sku: "TAMPA-4",
    price: null,
    show_price: false,
    is_best_seller: false,
    is_active: true,
    stock_status: "disponivel",
    main_image_url: "https://cdn.awsli.com.br/800x800/631/631138/produto/225130986/1-p0y0ox9egh.png",
    images: ["https://cdn.awsli.com.br/800x800/631/631138/produto/225130986/1-p0y0ox9egh.png"],
    specs: [{ spec_name: "Material", spec_value: "Chapa de aço 5mm" }, { spec_name: "Aplicação", spec_value: "Poços artesianos, tubo geomecânico 4\"" }],
    variations: [{ id: "vg-prod-38-1", name: "Diâmetro nominal", options: [{ id: "vo-prod-38-1-1", value: "4\" X FURO 1 1/2\"", price_delta: 0 }, { id: "vo-prod-38-1-2", value: "4\" X FURO 1 1/4\"", price_delta: 0 }, { id: "vo-prod-38-1-3", value: "4\" X FURO 1\"", price_delta: 0 }] }],
  },
];

export function getMockProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}

export function getMockRelatedProducts(product: Product, limit = 4): Product[] {
  return mockProducts
    .filter((p) => p.id !== product.id && p.category_id === product.category_id)
    .slice(0, limit)
    .concat(
      mockProducts.filter((p) => p.id !== product.id && p.category_id !== product.category_id).slice(0, Math.max(0, limit - 1))
    )
    .slice(0, limit);
}

export function getMockCategoryBySlug(slug: string): Category | undefined {
  return mockCategories.find((c) => c.slug === slug);
}

export function getMockBrandBySlug(slug: string): Brand | undefined {
  return mockBrands.find((b) => b.slug === slug);
}
